#!/bin/sh

clas12="${CLARA_HOME}/plugins/clas12"
classpath="${CLARA_HOME}/lib/*:${clas12}/lib/*:${clas12}/services/*"
orchestrator=org.jlab.clas.std.orchestrators.CloudOrchestrator

if [ -n "${JAVA_HOME}" ]; then
    java_bin="${JAVA_HOME}"
else
    java_bin=java
fi

"${java_bin}" -cp "${classpath}" ${orchestrator} "$@"
