#!/bin/sh
JVMOPTIONS=""
CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/services/*"
MAIN=org.jlab.clas.std.orchestrators.LocalOrchestrator

usage()
{
    cat << EOF
usage: $(basename $0) [ -t <threads> ] <services-file> <input-file> <output-file>
EOF
}

if [ "$#" = 0 ]; then
    usage
    exit 1
fi

java $JVMOPTIONS -cp $CLASSPATH $MAIN "$@"
